
- hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
    - role: caddy_ansible.caddy_ansible
      caddy_systemd_capabilities_enabled: false    
      caddy_config: |
        files.example.com
        encode gzip
        file_server browse {
            root /root/despiegk
        }