version: "3.1"
services:
  groupoffice:
    image: intermesh/groupoffice:latest
    container_name: groupoffice
    restart: always
    ports:
      - "7000:80"
    links:
      - db
    volumes:
      - "godata:/var/lib/groupoffice:cached"
      - "goetc:/etc/groupoffice:cached"
      - "gostudio:/usr/local/share/groupoffice/go/modules/studio:cached"
      # - ./src/studio:/usr/local/share/groupoffice/go/modules/studio
      # - "./config/ssl/groupoffice:/etc/ssl/groupoffice"
    env_file:
      - ./db.env     
  db:
    image: mariadb
    container_name: groupofficedb
    restart: always    
    env_file:
      - ./db.env
    environment:
      MYSQL_ROOT_PASSWORD: groupoffice
    volumes:
      - "dbdata:/var/lib/mysql:cached"
    ports:
      - "3306:3306"      
volumes:
  godata:
    name: godata
  goetc:
    name: goetc
  gostudio:
    name: gostudio
  dbdata:
    name: dbdata
