
- hosts: 127.0.0.1
  connection: local
  roles:
    - role: cloudalchemy.grafana
      vars:
        grafana_use_provisioning: true
        grafana_security:
          admin_user: admin
          admin_password: 123456  
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: 'http://localhost'
            basicAuth: false
        # grafana_dashboards:
        #   - dashboard_id: 111
        #     revision_id: 1
        #     datasource: prometheus    