networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
      driver: default
services:
  nats-1:
    command:
      - "-js"
      - "-c"
      - "/cfg/main.cfg"
    image: "nats:latest"
    networks:
      - main
    ports:
      - "14222:4222"
      - "16222:6222"
      - "18222:8222"
    volumes:
      - ./cfg:/cfg
      - /tmp/data:/data  
  tools:
    image: "base:latest"
    networks:
      - main    
    volumes:
      - ./scripts:/scripts
      - ~/myhost/alpine:/source        
  tarantool1:
    image: tarantool/tarantool:latest
    # environment:
    #   TARANTOOL_REPLICATION: "tarantool1,tarantool2"
    networks:
      - main
    ports:
      - "13301:3301"
